name: Build and Release Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Build Electron App
        run: npx electron-builder --publish never

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: BẢN CẬP NHẬT MỚI NHẤT
          make_latest: true
          files: |
            dist_electron/*.exe
            dist_electron/*.AppImage
            releases/*.apk
